### PR TITLE
matching drush to travis

### PR DESCRIPTION
**Pull request by lutaylor**
https://github.com/Islandora-Labs/islandora_vagrant_base_box/issues/8

Matching drush version with what is currently in travis for release. Travis would need to be updated and ensure no tests fail before we can move base box to drush 7. This should be considered for next release but it is out of scope of islandora_vagrant_base_box issue. We should always match community deployment guide and vagrant box drush version to what is currently in Travis.

To test bring up vagrant box based on pull and ensure drush version is 6.3.0 and that you can run drush commands as expected.

### CODE REVIEW

**Comment by lutaylor** [comment]
Note the build error seems to be a seperate issue from drush version.

**Comment by DonRichards** [comment]
OK, having it check again. There was an error not related to this pull as you suggested.

**Comment by DonRichards** [comment]
This is a bigger issue that needs to be addressed first. The build is no longer supported but this repo is pointing a pull request branch that no longer exist and can't be updated directly.

**Comment by DonRichards** [comment]
Looks like the drush commands are working. I'll merge this. Thanks @lutaylor for the update

**Comment by lutaylor** [comment]
@ruebot 

We are ready if you are. Did you need us to do anything to get this on atlas?

**Comment by lutaylor** [comment]
@ruebot 
Thanks!

**Comment by DonRichards** [comment]
I was able to get it to build without an issue. Do you know where Sleuthkit is failing? I added a few ignore shellcheck rules for SC1090 and SC1090. The only log chang was any time a "cd " happened the linting required a " || exit". This may be pointing to an error in the code. Perhaps one of the "cd " directories don't actually exist and before this change it went unnoticed.

**Comment by DonRichards** [comment]
Oh gotcha. That makes way more sense. I'd say go for it. @lutaylor your thoughts?

**Comment by DonRichards** [comment]
:-( You sure you don't want to do it? I figured. I'll make the changes and have @lutaylor check them as well.

**Comment by DonRichards** [comment]
You suggest the 4.2.0 release instead? Do you know if that version was working for us in the past?

**Comment by DonRichards** [comment]
We didn't specify a version before that commit so I'm still a little confused. Their most recent update was 4 days ago. 
The script does a pull from their repo/head. They've had 5 pulls in the last 2 weeks. None of which look relevant to this issue (ntfs_attrlist processing, auto type for OSX, memory leak, visual studio). 

"...check out the version of Sleuthkit before that commit" meaning which commit? A pull request, a solid version like 4.3 or 4.2, I'm not sure what you're suggesting. I am open to your thoughts on this, just attempting to clarify.

**Comment by DonRichards** [comment]
I could always switch 
`git clone https://github.com/sleuthkit/sleuthkit.git` **to** `git clone -b sleuthkit-4.2.0 https://github.com/sleuthkit/sleuthkit.git`

**Comment by DonRichards** [comment]
@ruebot This is referencing the parent of this commit sleuthkit/sleuthkit@f22fbda. I haven't done a pull request yet but do you think this is more along the lines you were suggesting?

**Comment by DonRichards** [comment]
Thanks for the help on this. This gives a much needed guidance on how these repos should be addressed and more understanding on how to test.

**Comment by DonRichards** [comment]
So this is my proposed solution to test if this would work. I'll make a new ticket. 
```terminal
$ rm -rf /tmp/sleuthkit
$ cd /tmp
$ git clone -o 5f8a005475c3ea3e6547c3276aea381e9804c005 https://github.com/sleuthkit/sleuthkit.git && cd sleuthkit && ./bootstrap && ./configure && make && make install && ldconfig
```

**Comment by lutaylor** [comment]
This seems to work for some reason the git clone till pulls against head 

https://github.com/Islandora-Labs/islandora_vagrant_base_box/pull/16

**Comment by lutaylor** [comment]
Generally I have always pulled repos from specific git commits vs HEAD since we have no control over when HEAD gets updated and could break something.

**Pull request merged**
