### PR TITLE
Ghostscript Update

### PR DESCRIPTION
**Pull request by lutaylor**
**JIRA Ticket**: 
https://jira.duraspace.org/browse/ISLANDORA-2035

* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)
https://github.com/Islandora/islandora_paged_content/commit/723004bb732d171ae7ad49f994878cc454641629
https://github.com/Islandora/islandora_paged_content/pull/137
Issue link https://github.com/Islandora-Labs/islandora_vagrant/issues/127

# What does this Pull Request do?

Updates Ghostscript to latest version 9.23 which should allow for compression. 

# What's new?
Updated Ghostscript version to the latest. 

# How should this be tested?
vagrant up
gs -v
Should show Ghostscript version 9.23. 
If it shows any other version or the gs -v command fails to run then the test should be considered failed. 

The box should be re-exported to ensure it still works with latest Islandora. 

As per Islandora-Labs/islandora_vagrant#127

> Ingest 2 newspapers (ideally multiple pages)
> Using a PDF
> 1st newspaper PDF should use the PAGE IMAGE SETTINGS at the upload page of 48-bit RGB, 150 DPI or 300 DPI with Extract text from the PDF
> 2nd newspaper PDF should use the PAGE IMAGE SETTINGS at the upload page of 32-bit CMYK, 300 DPI with Extract text from the PDF
> Check if derivatives were properly generated

# Additional Notes:
Completely optional PR we might want to think about sticking with 9.10 just for legacy reasons since it is still being maintained for security patches by Ubuntu.

Either way, we should be able to close out Issue link https://github.com/Islandora-Labs/islandora_vagrant/issues/127

# Interested parties
@DonRichards @Islandora-Labs/committers

### CODE REVIEW

**Comment by DonRichards** [comment]
@lutaylor Under the "How should this be tested" section is should say what would fail if this Ghostscript change fails?

**Comment by DonRichards** [comment]
@lutaylor 2 questions. How do you suggest I test if upgrading Ghostscript isn't breaking anything (image ingest, book, etc) and would you mind correcting the code travis is complaining about?

**Comment by DonRichards** [comment]
Sorry, I know it sounds a little dumbed down asking what should be tested but I have found it immensely helpful in the past. So small changes like this might have massive effects on seemingly unrelated functions.

**Comment by lutaylor** [comment]
Your test case mentioned here should do perfectly https://github.com/Islandora-Labs/islandora_vagrant/issues/127 


> Ingest 2 newspapers (ideally multiple pages)
> Using a PDF
> 1st newspaper PDF should use the PAGE IMAGE SETTINGS at the upload page of 48-bit RGB, 150 DPI or 300 DPI with Extract text from the PDF
> 2nd newspaper PDF should use the PAGE IMAGE SETTINGS at the upload page of 32-bit CMYK, 300 DPI with Extract text from the PDF
> Check if derivatives were properly generated

Ok to use this?

**Comment by lutaylor** [comment]
I fixed the travis check.

**Comment by lutaylor** [comment]
@DonRichards 
I see you approved the changes did you want to merge?

**Comment by DonRichards** [comment]
Apologies. Meant to merge it yesterday.

**Pull request merged**
