### PR TITLE
add drupal 7 indicator to the drush download, so it does not default …

### PR DESCRIPTION
**Pull request by pc37utn**
…to 8.

### CODE REVIEW

**Comment by pc37utn** [comment]
@lutaylor  @DonRichards    I might have jumped too fast on this, it showed up when I was doing something with a centos7 base box made from this on, I think it might have been because the drush version in centos7 is 8.x.

**Comment by DonRichards** [comment]
@pc37utn I can test it but I can't merge because we share an office location

**Comment by lutaylor** [comment]
@DonRichards @pc37utn 

I have not been able to replicate the issue, always downloads Drupal 7. It must just be the default with drush 8.x

**Comment by pc37utn** [comment]
I did another clean buil;d of base box and it did not do that, I think it was just the drush 8 that affected it.  I'll close this but if we ever go to drush 8 we'll need to add it back in.

**Pull request closed without merging**
